/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 helmet.gltf --transform
Author: The Royal Armoury (Livrustkammaren) (https://sketchfab.com/TheRoyalArmoury)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/helmet-with-beaked-visor-47bd6028d3244fa5b698388a9a6dda38
Title: Helmet with Beaked Visor
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/helmet-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-1.3, 0.41, 2.38]} rotation={[-Math.PI / 2, 0.08, 0.54]} scale={0.01}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.model_Material_u1_v1} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.model_Material_u1_v1} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.model_Material_u1_v1} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.model_Material_u1_v1} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.model_Material_u1_v1} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.model_Material_u1_v1} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.model_Material_u1_v1} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.model_Material_u1_v1} />
        <mesh geometry={nodes.Object_10.geometry} material={materials.model_Material_u1_v1} />
        <mesh geometry={nodes.Object_11.geometry} material={materials.model_Material_u1_v1} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.model_Material_u1_v1} />
      </group>
    </group>
  )
}

useGLTF.preload('/helmet-transformed.glb')
